import { ai } from './helpers';
import { TAGS } from './helpers';
import type { AiProfile } from './types';

export const battleAis: AiProfile[] = [
  ai({
    id: 'warmup-bot',
    level: 0,
    name: 'Warmup Bot',
    role: 'warmup',
    summary: 'Legal moves only, with a gentle center bias and little tactical awareness.',
    strengths: ['Never cheats', 'Keeps the game moving', 'Helps with onboarding'],
    tacticalBudgetMs: 10,
    searchDepth: 0,
    openingBias: ['center', 'adjacent-center'],
    reviewTags: [TAGS.rules, TAGS.center],
  }),
  ai({
    id: 'block-baron',
    level: 1,
    name: 'Block Baron',
    role: 'battle',
    summary: 'Sees immediate wins and blocks, then chooses a simple heuristic move.',
    strengths: ['Catches one-move tactics', 'Stays very fast', 'Punishes obvious blunders'],
    tacticalBudgetMs: 20,
    searchDepth: 1,
    openingBias: ['center', 'block-threat'],
    reviewTags: [TAGS.winIn1, TAGS.blockIn1],
  }),
  ai({
    id: 'center-sentinel',
    level: 2,
    name: 'Center Sentinel',
    role: 'battle',
    summary: 'Prefers the middle, checks tactical replies, and searches a little deeper.',
    strengths: ['Center control', 'Basic tactical hygiene', 'Quick opening play'],
    tacticalBudgetMs: 30,
    searchDepth: 2,
    openingBias: ['center', 'adjacent-center'],
    reviewTags: [TAGS.center, TAGS.opening],
  }),
  ai({
    id: 'threat-smith',
    level: 3,
    name: 'Threat Smith',
    role: 'battle',
    summary: 'Builds pressure, hunts forcing moves, and avoids the most obvious traps.',
    strengths: ['Threat creation', 'Forcing lines', 'Safer shape choices'],
    tacticalBudgetMs: 45,
    searchDepth: 3,
    openingBias: ['center', 'threat-build'],
    reviewTags: [TAGS.threat, TAGS.review],
  }),
  ai({
    id: 'forksmith',
    level: 4,
    name: 'Forksmith',
    role: 'boss',
    summary: 'Recognizes and creates double threats, especially in shapes that look quiet.',
    strengths: ['Fork detection', 'Tactical sequencing', 'Punishes single-answer positions'],
    tacticalBudgetMs: 70,
    searchDepth: 4,
    openingBias: ['center', 'fork-prep'],
    reviewTags: [TAGS.doubleThreat, TAGS.threat],
  }),
  ai({
    id: 'diagonal-djinn',
    level: 5,
    name: 'Diagonal Djinn',
    role: 'boss',
    summary: 'Rewards support-square awareness and tracks diagonal danger better than the mid tiers.',
    strengths: ['Diagonal pressure', 'Support-square awareness', 'Good structural play'],
    tacticalBudgetMs: 80,
    searchDepth: 4,
    openingBias: ['center', 'diagonal-prep'],
    reviewTags: [TAGS.diagonal, TAGS.defense],
  }),
  ai({
    id: 'parity-phantom',
    level: 6,
    name: 'Parity Phantom',
    role: 'boss',
    summary: 'Uses parity-aware evaluation and leans into positions that force awkward access.',
    strengths: ['Odd/even awareness', 'Endgame pressure', 'Quietly poisonous moves'],
    tacticalBudgetMs: 100,
    searchDepth: 5,
    openingBias: ['center', 'parity-prep'],
    reviewTags: [TAGS.parity, TAGS.endgame],
  }),
  ai({
    id: 'mirror-master',
    level: 7,
    name: 'Mirror Master',
    role: 'boss',
    summary: 'Uses a compact opening book and punishes careless early structure.',
    strengths: ['Opening structure', 'Mirror responses', 'Good first-six-ply play'],
    tacticalBudgetMs: 120,
    searchDepth: 5,
    openingBias: ['center', 'book-line'],
    reviewTags: [TAGS.opening, TAGS.center],
  }),
  ai({
    id: 'endgame-engine',
    level: 8,
    name: 'Endgame Engine',
    role: 'boss',
    summary: 'The strongest battle AI, with a deeper worker budget, cache hits, and practical selective search.',
    strengths: ['Iterative deepening', 'Transposition hits', 'Late-game conversion'],
    tacticalBudgetMs: 150,
    searchDepth: 6,
    openingBias: ['center', 'book-line', 'threat-build'],
    reviewTags: [TAGS.endgame, TAGS.review],
  }),
  ai({
    id: 'oracle',
    level: 9,
    name: 'Oracle',
    role: 'analysis',
    summary: 'Post-game analysis that labels the best, good, inaccurate, mistaken, and blundered moves.',
    strengths: ['Deeper background analysis', 'Concept tagging', 'Post-game review'],
    tacticalBudgetMs: 200,
    searchDepth: 7,
    openingBias: ['center', 'book-line', 'parity-prep'],
    reviewTags: [TAGS.review, TAGS.endgame, TAGS.parity],
  }),
];

export const battleAiById = new Map(battleAis.map((profile) => [profile.id, profile]));
export const battleBossIds = battleAis
  .filter((profile) => profile.level >= 1 && profile.level <= 8)
  .map((profile) => profile.id);
export const analysisOracle = battleAiById.get('oracle')!;
