import { lesson, note, pos, step, world } from './helpers';
import type { LessonDef, WorldDef } from './types';
import { TAGS } from './helpers';

const concept = (
  id: string,
  title: string,
  prompt: string,
  reviewTags: LessonDef['tags'],
  opts: Partial<Pick<ReturnType<typeof step>, 'position' | 'coachNotes' | 'successMessage' | 'failureMessage'>> = {},
) =>
  step({
    id,
    type: 'concept',
    title,
    prompt,
    reviewTags,
    ...opts,
  });

const guided = (
  id: string,
  title: string,
  prompt: string,
  position: NonNullable<ReturnType<typeof step>['position']>,
  acceptedColumns: number[],
  reviewTags: LessonDef['tags'],
  opts: Partial<Pick<ReturnType<typeof step>, 'coachNotes' | 'hintColumns' | 'successMessage' | 'failureMessage'>> = {},
) =>
  step({
    id,
    type: 'guided',
    title,
    prompt,
    position,
    acceptedColumns,
    reviewTags,
    ...opts,
  });

const drill = (
  id: string,
  title: string,
  prompt: string,
  position: NonNullable<ReturnType<typeof step>['position']>,
  acceptedColumns: number[],
  reviewTags: LessonDef['tags'],
  opts: Partial<Pick<ReturnType<typeof step>, 'coachNotes' | 'hintColumns' | 'successMessage' | 'failureMessage'>> = {},
) =>
  step({
    id,
    type: 'drill',
    title,
    prompt,
    position,
    acceptedColumns,
    reviewTags,
    ...opts,
  });

const puzzle = (
  id: string,
  title: string,
  prompt: string,
  position: NonNullable<ReturnType<typeof step>['position']>,
  acceptedColumns: number[],
  reviewTags: LessonDef['tags'],
  opts: Partial<Pick<ReturnType<typeof step>, 'coachNotes' | 'hintColumns' | 'successMessage' | 'failureMessage'>> = {},
) =>
  step({
    id,
    type: 'puzzle',
    title,
    prompt,
    position,
    acceptedColumns,
    reviewTags,
    ...opts,
  });

const battleStep = (
  id: string,
  title: string,
  prompt: string,
  reviewTags: LessonDef['tags'],
  opts: Partial<Pick<ReturnType<typeof step>, 'position' | 'coachNotes' | 'successMessage' | 'failureMessage'>> = {},
) =>
  step({
    id,
    type: 'battle',
    title,
    prompt,
    reviewTags,
    ...opts,
  });

const boss = (
  id: string,
  title: string,
  prompt: string,
  reviewTags: LessonDef['tags'],
  opts: Partial<Pick<ReturnType<typeof step>, 'position' | 'coachNotes' | 'successMessage' | 'failureMessage'>> = {},
) =>
  step({
    id,
    type: 'boss',
    title,
    prompt,
    reviewTags,
    ...opts,
  });

const lessonDef = (data: LessonDef): LessonDef => lesson(data);

const empty = pos([], 'human', 'opening board');
const centerOpen = pos([], 'human', 'center-first opening');
const stackLeft = pos([2, 6], 'human', 'stack-left opening');
const verticalWinLeft = pos([2, 6, 2, 7, 2, 5], 'human', 'human has a vertical win on column 2');
const blockThree = pos([1, 3, 2, 3, 4, 3], 'human', 'cpu threatens column 3');
const horizontalWinRight = pos([2, 1, 3, 1, 4, 7], 'human', 'bottom-row line with one clean open end');
const supportRace = pos([4, 3, 4, 3, 5, 2], 'human', 'simple support race');
const forkPrep = pos([4, 2, 4, 2, 5, 3, 6, 7], 'human', 'fork-prep lane');
const diagonalSupportWin = pos(
  [1, 2, 2, 3, 5, 3, 3, 4, 6, 4, 7, 4],
  'human',
  'supported diagonal with one landing square',
);
const diagonalPrep = pos([4, 5, 5, 6, 6, 7], 'human', 'diagonal staircase');
const parityPrep = pos([4, 3, 4, 3, 5, 2, 5, 2], 'human', 'odd-even access tension');
const poisonedParityPrep = pos([4, 3, 4, 3, 5, 2, 1, 6], 'human', 'poisoned parity setup');
const mirrorPrep = pos([4, 4, 3, 3, 5, 2, 1, 1], 'human', 'mirror opening tension');
const mirrorPunish = pos([4, 4, 3, 3, 5, 5, 1, 6], 'human', 'mirror punish window');
const endgamePrep = pos([4, 1, 4, 2, 3, 2, 3, 6], 'human', 'late-position squeeze');

const world0Lessons = [
  lessonDef({
    id: 'world-0-board-and-gravity',
    worldId: 'world-0',
    slug: 'board-and-gravity',
    title: 'Board and Gravity',
    estMinutes: 4,
    tags: [TAGS.rules],
    prerequisites: [],
    summary: 'Teach the grid, the drop rule, and the first click with almost no friction.',
    steps: [
      guided(
        'world-0-board-and-gravity-first-drop',
        'Watch gravity work',
        'Drop a chip anywhere and watch it settle into the lowest open cell.',
        empty,
        [1, 2, 3, 4, 5, 6, 7],
        [TAGS.rules],
        {
          coachNotes: [note('gravity', TAGS.rules, 'Gravity first', 'Every move is a column choice, not a row choice.')],
          hintColumns: [4],
          successMessage: 'Good. The chip always falls to the lowest open cell.',
          failureMessage: 'Pick any legal column and watch where the chip lands.',
        },
      ),
      guided(
        'world-0-board-and-gravity-stack',
        'Stack in the same column',
        'Drop in the same column again and watch the new chip land on top of the old one.',
        stackLeft,
        [2],
        [TAGS.rules],
        {
          hintColumns: [2],
          successMessage: 'Exactly. Filled cells hold the next chip up.',
          failureMessage: 'Use the same column again and notice the stack grow upward.',
        },
      ),
      drill(
        'world-0-board-and-gravity-drill',
        'Use the center',
        'Start from the center. It stays easiest to build from later.',
        centerOpen,
        [4],
        [TAGS.rules, TAGS.center],
        {
          coachNotes: [note('center-start', TAGS.center, 'Center is stable', 'It leaves the most future lines open.')],
          hintColumns: [4],
          successMessage: 'You found the safest first reference point.',
        },
      ),
    ],
  }),
  lessonDef({
    id: 'world-0-three-win-directions',
    worldId: 'world-0',
    slug: 'three-win-directions',
    title: 'Three win directions',
    estMinutes: 4,
    tags: [TAGS.rules, TAGS.winIn1],
    prerequisites: ['world-0-board-and-gravity'],
    summary: 'Show vertical, horizontal, and diagonal wins as one family of patterns.',
    steps: [
      concept(
        'world-0-three-win-directions-concept',
        'A four-in-a-row can point three ways',
        'You can win vertically, horizontally, or on a diagonal. The board changes, but the search habit is the same.',
        [TAGS.rules, TAGS.winIn1],
        {
          position: verticalWinLeft,
          coachNotes: [note('three-lines', TAGS.rules, 'One rule, three directions', 'Look for the missing fourth chip in the line.')],
        },
      ),
      guided(
        'world-0-three-win-directions-guided-vertical',
        'Complete the vertical win',
        'This column already has three of yours. Finish the stack.',
        verticalWinLeft,
        [2],
        [TAGS.winIn1],
        {
          hintColumns: [2],
          successMessage: 'That is a clean win in one.',
          failureMessage: 'Search for the column with three of your chips already stacked.',
        },
      ),
      guided(
        'world-0-three-win-directions-guided-horizontal',
        'Complete the horizontal win',
        'The bottom row already has three in a row. Close the line on the right.',
        horizontalWinRight,
        [5],
        [TAGS.winIn1],
        {
          hintColumns: [5],
          successMessage: 'You saw the horizontal line before it closed on you.',
          failureMessage: 'Look for the open end of the row.',
        },
      ),
    ],
  }),
  lessonDef({
    id: 'world-0-first-win',
    worldId: 'world-0',
    slug: 'first-win',
    title: 'Your first win',
    estMinutes: 4,
    tags: [TAGS.winIn1, TAGS.rules],
    prerequisites: ['world-0-three-win-directions'],
    summary: 'Turn the rule into a habit by spotting easy wins before anything else.',
    steps: [
      drill(
        'world-0-first-win-drill-1',
        'Win in one',
        'Take the obvious win without overthinking it.',
        verticalWinLeft,
        [2],
        [TAGS.winIn1],
        {
          hintColumns: [2],
          successMessage: 'Fast and clean. Winning first keeps the rest of the board honest.',
        },
      ),
      puzzle(
        'world-0-first-win-puzzle',
        'Find the second win',
        'The same idea appears again in a different column. Read the stack, then strike.',
        pos([2, 1, 2, 1, 2, 1], 'human', 'alternate vertical pattern'),
        [2],
        [TAGS.winIn1],
        {
          hintColumns: [2],
          coachNotes: [note('stack-win', TAGS.winIn1, 'Stacked win', 'If three of yours are stacked, the fourth is usually one click away.')],
          successMessage: 'You found the repeated pattern, not just the first example.',
        },
      ),
    ],
  }),
  lessonDef({
    id: 'world-0-first-block',
    worldId: 'world-0',
    slug: 'first-block',
    title: 'Your first required block',
    estMinutes: 4,
    tags: [TAGS.blockIn1, TAGS.defense],
    prerequisites: ['world-0-first-win'],
    summary: 'Teach the mirror habit: if they can win now, blocking is not optional.',
    steps: [
      concept(
        'world-0-first-block-concept',
        'Blocks are urgent',
        'If the CPU already has three in a line, stopping that line comes before any prettier plan.',
        [TAGS.blockIn1, TAGS.defense],
        {
          position: blockThree,
          coachNotes: [note('block-now', TAGS.blockIn1, 'Block now', 'A one-move loss is never worth a long-term idea.')],
        },
      ),
      guided(
        'world-0-first-block-guided',
        'Block the threat',
        'The CPU is threatening a win in column 3. Cut it off immediately.',
        blockThree,
        [3],
        [TAGS.blockIn1],
        {
          hintColumns: [3],
          successMessage: 'Good. You removed the immediate loss.',
          failureMessage: 'Find the CPU stack of three and cover its open end.',
        },
      ),
    ],
  }),
  lessonDef({
    id: 'world-0-warmup-bot',
    worldId: 'world-0',
    slug: 'warmup-bot',
    title: 'Warmup Bot',
    estMinutes: 3,
    tags: [TAGS.rules, TAGS.review],
    prerequisites: ['world-0-first-block'],
    bossAiId: 'warmup-bot',
    summary: 'A very soft first boss that confirms the rules are usable in a live game.',
    steps: [
      battleStep(
        'world-0-warmup-bot-battle',
        'Play a short game',
        'The Warmup Bot only plays legal moves. Keep the scan simple: win, block, improve shape.',
        [TAGS.rules, TAGS.review],
        {
          position: empty,
          coachNotes: [note('scan-order', TAGS.review, 'Scan order', 'Check win now, then block now, then improve the shape.')],
          successMessage: 'You survived the first live loop.',
        },
      ),
      boss(
        'world-0-warmup-bot-boss',
        'Boss wrap-up',
        'Finish the lesson by noticing at least one tactical moment from the game.',
        [TAGS.rules, TAGS.review],
        {
          successMessage: 'The first boss is about making the board feel familiar, not hard.',
        },
      ),
    ],
  }),
];

const world1Lessons = [
  lessonDef({
    id: 'world-1-scan-order',
    worldId: 'world-1',
    slug: 'scan-order',
    title: 'The scan order',
    estMinutes: 4,
    tags: [TAGS.winIn1, TAGS.blockIn1, TAGS.review],
    prerequisites: ['world-0-warmup-bot'],
    summary: 'Lock in the exact move-checking order that prevents beginner blunders.',
    steps: [
      concept(
        'world-1-scan-order-concept',
        'Look for wins before plans',
        'Every turn starts the same way: can I win now, must I block now, and only then should I shape the board?',
        [TAGS.winIn1, TAGS.blockIn1, TAGS.review],
        {
          position: horizontalWinRight,
          coachNotes: [note('scan-first', TAGS.review, 'Scan first', 'A quick tactical scan is faster than a long explanation.')],
        },
      ),
      guided(
        'world-1-scan-order-guided-win',
        'Identify the win',
        'This is a one-move win, so the scan stops immediately.',
        horizontalWinRight,
        [5],
        [TAGS.winIn1],
        {
          hintColumns: [5],
          successMessage: 'You stopped at the first rule: can I win now?',
        },
      ),
      guided(
        'world-1-scan-order-guided-block',
        'Identify the block',
        'If the opponent has the win, your scan ends in defense.',
        blockThree,
        [3],
        [TAGS.blockIn1],
        {
          hintColumns: [3],
          successMessage: 'The block came before any stylistic idea.',
        },
      ),
    ],
  }),
  lessonDef({
    id: 'world-1-mixed-tactics',
    worldId: 'world-1',
    slug: 'mixed-tactics',
    title: 'Mixed tactics',
    estMinutes: 5,
    tags: [TAGS.winIn1, TAGS.blockIn1, TAGS.review],
    prerequisites: ['world-1-scan-order'],
    summary: 'Blend win-in-one and block-in-one positions so the habit becomes automatic.',
    steps: [
      drill(
        'world-1-mixed-tactics-drill-1',
        'Win or block?',
        'Decide whether this position belongs to offense or defense first.',
        supportRace,
        [4],
        [TAGS.review, TAGS.winIn1],
        {
          hintColumns: [4],
          coachNotes: [note('win-or-block', TAGS.review, 'Win or block', 'Do not look for shape before the tactical check finishes.')],
        },
      ),
      puzzle(
        'world-1-mixed-tactics-puzzle-1',
        'Immediate defense',
        'This one looks active, but the safe move is still the defensive answer.',
        blockThree,
        [3],
        [TAGS.blockIn1, TAGS.review],
        {
          hintColumns: [3],
          failureMessage: 'The opponent’s threat is the strongest thing on the board.',
        },
      ),
    ],
  }),
  lessonDef({
    id: 'world-1-speed-drills',
    worldId: 'world-1',
    slug: 'speed-drills',
    title: 'Speed drills',
    estMinutes: 5,
    tags: [TAGS.winIn1, TAGS.blockIn1, TAGS.review],
    prerequisites: ['world-1-mixed-tactics'],
    summary: 'Build the reflex without turning the exercise into a stress test.',
    steps: [
      drill(
        'world-1-speed-drills-drill-1',
        'Snap win',
        'This is the same win-in-one pattern at a new board address.',
        horizontalWinRight,
        [5],
        [TAGS.winIn1],
        { hintColumns: [5], successMessage: 'The pattern is familiar now.' },
      ),
      drill(
        'world-1-speed-drills-drill-2',
        'Snap block',
        'Block the only immediate loss before you think about anything else.',
        blockThree,
        [3],
        [TAGS.blockIn1],
        { hintColumns: [3], successMessage: 'You kept the game alive.' },
      ),
    ],
  }),
  lessonDef({
    id: 'world-1-block-baron',
    worldId: 'world-1',
    slug: 'block-baron',
    title: 'Block Baron',
    estMinutes: 4,
    tags: [TAGS.blockIn1, TAGS.review],
    prerequisites: ['world-1-speed-drills'],
    bossAiId: 'block-baron',
    summary: 'A tactical boss that punishes missed immediate wins and missed blocks.',
    steps: [
      battleStep(
        'world-1-block-baron-battle',
        'Play Block Baron',
        'The boss is simple but ruthless: if you ignore a tactic, it will cash it in immediately.',
        [TAGS.blockIn1, TAGS.review],
        {
          position: supportRace,
          coachNotes: [note('baron', TAGS.blockIn1, 'Baron rule', 'Immediate tactics are the whole fight here.')],
        },
      ),
      boss(
        'world-1-block-baron-boss',
        'Checkpoint',
        'Finish by naming the first thing you checked each turn.',
        [TAGS.blockIn1, TAGS.review],
        { successMessage: 'The right answer is always the same: win, block, then build.' },
      ),
    ],
  }),
];

const world2Lessons = [
  lessonDef({
    id: 'world-2-center-control',
    worldId: 'world-2',
    slug: 'center-control',
    title: 'Center control',
    estMinutes: 5,
    tags: [TAGS.center, TAGS.opening],
    prerequisites: ['world-1-block-baron'],
    summary: 'Explain why the center column participates in the most future fours.',
    steps: [
      concept(
        'world-2-center-control-concept',
        'Why center matters',
        'The center column touches the most possible lines, so early center moves stay flexible longer.',
        [TAGS.center, TAGS.opening],
        {
          position: centerOpen,
          coachNotes: [note('center-lines', TAGS.center, 'Most lines pass through the center', 'Center control is not cosmetic; it is geometric.')],
        },
      ),
      guided(
        'world-2-center-control-guided',
        'Open in the center',
        'On an empty board, the center is the simplest strong answer.',
        centerOpen,
        [4],
        [TAGS.center, TAGS.opening],
        {
          hintColumns: [4],
          successMessage: 'Center is a stable home base.',
        },
      ),
    ],
  }),
  lessonDef({
    id: 'world-2-column-value',
    worldId: 'world-2',
    slug: 'column-value',
    title: 'Column value',
    estMinutes: 5,
    tags: [TAGS.center, TAGS.opening],
    prerequisites: ['world-2-center-control'],
    summary: 'Compare center, adjacent, and edge columns without overcomplicating the picture.',
    steps: [
      drill(
        'world-2-column-value-drill-1',
        'Choose the richer column',
        'This position gives you a choice between shape and reach. Pick the more flexible column.',
        supportRace,
        [4],
        [TAGS.center, TAGS.opening],
        {
          hintColumns: [4],
          successMessage: 'The middle keeps more options alive.',
        },
      ),
      puzzle(
        'world-2-column-value-puzzle-1',
        'Avoid the edge trap',
        'An edge move can look stable, but it often hands the center away for free.',
        pos([1, 4, 1, 4], 'human', 'edge-vs-center comparison'),
        [4],
        [TAGS.center, TAGS.opening],
        {
          hintColumns: [4],
          coachNotes: [note('edge-vs-center', TAGS.center, 'Edge later, center now', 'Edges usually matter less in the opening.')],
        },
      ),
    ],
  }),
  lessonDef({
    id: 'world-2-opening-punish',
    worldId: 'world-2',
    slug: 'opening-punish',
    title: 'Punish weak openings',
    estMinutes: 5,
    tags: [TAGS.center, TAGS.opening, TAGS.review],
    prerequisites: ['world-2-column-value'],
    summary: 'Show how careless opening play gives away board influence before the game matures.',
    steps: [
      guided(
        'world-2-opening-punish-guided-1',
        'Take the center back',
        'If the opponent drifted to the side, answer by reasserting center pressure.',
        pos([1, 7, 2, 6], 'human', 'opening with weak edges'),
        [4],
        [TAGS.center, TAGS.opening],
        { hintColumns: [4], successMessage: 'Center pressure survives the opening skirmish.' },
      ),
      drill(
        'world-2-opening-punish-drill-1',
        'Best opening move',
        'When the board is still young, ask whether the move improves future reach or only occupies space.',
        empty,
        [4],
        [TAGS.center, TAGS.opening],
        { hintColumns: [4], successMessage: 'You chose flexibility over vanity.' },
      ),
    ],
  }),
  lessonDef({
    id: 'world-2-center-sentinel',
    worldId: 'world-2',
    slug: 'center-sentinel',
    title: 'Center Sentinel',
    estMinutes: 4,
    tags: [TAGS.center, TAGS.opening, TAGS.review],
    prerequisites: ['world-2-opening-punish'],
    bossAiId: 'center-sentinel',
    summary: 'A boss that strongly prefers center control and punishes edge-first play.',
    steps: [
      battleStep(
        'world-2-center-sentinel-battle',
        'Play Center Sentinel',
        'If you ignore the center, this boss will own the middle of the board and make you feel it.',
        [TAGS.center, TAGS.opening],
        {
          position: centerOpen,
          coachNotes: [note('sentinel', TAGS.center, 'Center belongs to the player who wants future options', 'That is usually you.')],
        },
      ),
      boss(
        'world-2-center-sentinel-boss',
        'Center checkpoint',
        'Review the opening move that gave you the best long-term options.',
        [TAGS.center, TAGS.opening],
        { successMessage: 'A good opening is not flashy; it is durable.' },
      ),
    ],
  }),
];

const world3Lessons = [
  lessonDef({
    id: 'world-3-threats',
    worldId: 'world-3',
    slug: 'threats',
    title: 'Build threats',
    estMinutes: 5,
    tags: [TAGS.threat, TAGS.review],
    prerequisites: ['world-2-center-sentinel'],
    summary: 'Shift from reacting to creating moves the opponent must answer.',
    steps: [
      concept(
        'world-3-threats-concept',
        'Threats force attention',
        'A real threat is a move that makes the opponent respond instead of expanding their own plan.',
        [TAGS.threat, TAGS.review],
        {
          position: supportRace,
          coachNotes: [note('threat', TAGS.threat, 'Threats are pressure', 'A threat is only useful if it changes the opponent’s options.')],
        },
      ),
      guided(
        'world-3-threats-guided',
        'Create a threat',
        'Make a move that asks a question the opponent has to answer.',
        supportRace,
        [4],
        [TAGS.threat],
        { hintColumns: [4], successMessage: 'You created pressure instead of just occupancy.' },
      ),
    ],
  }),
  lessonDef({
    id: 'world-3-forcing-responses',
    worldId: 'world-3',
    slug: 'forcing-responses',
    title: 'Forcing responses',
    estMinutes: 5,
    tags: [TAGS.threat, TAGS.defense],
    prerequisites: ['world-3-threats'],
    summary: 'Teach the difference between a nice-looking move and a move that demands a reply.',
    steps: [
      drill(
        'world-3-forcing-responses-drill-1',
        'Which move forces a response?',
        'Choose the move that leaves the opponent without a comfortable pass.',
        pos([4, 3, 4, 3], 'human', 'forcing-response shape'),
        [4],
        [TAGS.threat],
        {
          hintColumns: [4],
          successMessage: 'That move changes the board, not just the vibe.',
        },
      ),
      puzzle(
        'world-3-forcing-responses-puzzle-1',
        'Threat or decoration?',
        'If the move does not make the opponent answer, it is not the lesson yet.',
        pos([2, 5, 2, 5, 4, 3], 'human', 'decorative shape'),
        [4],
        [TAGS.threat],
        {
          hintColumns: [4],
          coachNotes: [note('force', TAGS.threat, 'Force a reply', 'A threat is a demand, not a suggestion.')],
        },
      ),
    ],
  }),
  lessonDef({
    id: 'world-3-create-threats',
    worldId: 'world-3',
    slug: 'create-threats',
    title: 'Create threats in sequence',
    estMinutes: 5,
    tags: [TAGS.threat, TAGS.review],
    prerequisites: ['world-3-forcing-responses'],
    summary: 'Use a short sequence to teach how threat-building compounds over two moves.',
    steps: [
      guided(
        'world-3-create-threats-guided-1',
        'Build a second threat',
        'Your first threat is not enough if the follow-up is empty. Prepare the next question too.',
        forkPrep,
        [4],
        [TAGS.threat],
        { hintColumns: [4], successMessage: 'The board now carries a little pressure from your side.' },
      ),
      drill(
        'world-3-create-threats-drill-1',
        'Threat chain',
        'Play a move that creates pressure now and leaves room to keep the pressure next turn.',
        pos([4, 1, 4, 1, 3, 2], 'human', 'simple threat chain'),
        [3],
        [TAGS.threat],
        { hintColumns: [3], successMessage: 'You chose continuity over a one-shot idea.' },
      ),
    ],
  }),
  lessonDef({
    id: 'world-3-threat-smith',
    worldId: 'world-3',
    slug: 'threat-smith',
    title: 'Threat Smith',
    estMinutes: 4,
    tags: [TAGS.threat, TAGS.review],
    prerequisites: ['world-3-create-threats'],
    bossAiId: 'threat-smith',
    summary: 'The boss that rewards immediate pressure but is still light on deep parity ideas.',
    steps: [
      battleStep(
        'world-3-threat-smith-battle',
        'Play Threat Smith',
        'Look for pressure, not just safety. If you create a forcing move, this boss has to answer it.',
        [TAGS.threat, TAGS.review],
        {
          position: supportRace,
          coachNotes: [note('smith', TAGS.threat, 'Pressure earns replies', 'The best move is often the one that changes the opponent’s tempo.')],
        },
      ),
      boss(
        'world-3-threat-smith-boss',
        'Threat checkpoint',
        'Say which move on your last game made the opponent respond.',
        [TAGS.threat, TAGS.review],
        { successMessage: 'You are no longer just reacting to the board.' },
      ),
    ],
  }),
];

const world4Lessons = [
  lessonDef({
    id: 'world-4-fork-recognition',
    worldId: 'world-4',
    slug: 'fork-recognition',
    title: 'Recognize forks',
    estMinutes: 5,
    tags: [TAGS.doubleThreat, TAGS.review],
    prerequisites: ['world-3-threat-smith'],
    summary: 'Introduce the single most practical advanced idea: one block is not enough.',
    steps: [
      concept(
        'world-4-fork-recognition-concept',
        'A fork asks for two answers',
        'A double threat wins because the opponent can answer only one of the two lines.',
        [TAGS.doubleThreat, TAGS.review],
        {
          position: forkPrep,
          coachNotes: [note('fork', TAGS.doubleThreat, 'Two answers, one turn', 'If a move creates two independent wins, you are in fork territory.')],
        },
      ),
      guided(
        'world-4-fork-recognition-guided',
        'Spot the fork',
        'Find the move that turns one threat into two.',
        forkPrep,
        [4],
        [TAGS.doubleThreat],
        { hintColumns: [4], successMessage: 'You saw the shape that makes one block too small.' },
      ),
    ],
  }),
  lessonDef({
    id: 'world-4-fork-construction',
    worldId: 'world-4',
    slug: 'fork-construction',
    title: 'Construct forks',
    estMinutes: 5,
    tags: [TAGS.doubleThreat, TAGS.threat],
    prerequisites: ['world-4-fork-recognition'],
    summary: 'Build forks by preparing support instead of swinging at the first chance.',
    steps: [
      drill(
        'world-4-fork-construction-drill-1',
        'Set the fork',
        'Choose the move that prepares two future wins at once.',
        forkPrep,
        [4],
        [TAGS.doubleThreat, TAGS.threat],
        { hintColumns: [4], successMessage: 'You are building a position, not just a move.' },
      ),
      puzzle(
        'world-4-fork-construction-puzzle-1',
        'Hidden fork',
        'A good attacking move can still be too slow if it does not create a second demand.',
        pos([4, 2, 4, 2, 5, 3], 'human', 'hidden fork setup'),
        [4],
        [TAGS.doubleThreat],
        { hintColumns: [4], coachNotes: [note('hidden-fork', TAGS.doubleThreat, 'Hidden fork', 'The board can look calm right before the fork appears.')], successMessage: 'You preferred the forcing move over the flashy one.' },
      ),
    ],
  }),
  lessonDef({
    id: 'world-4-fork-defense',
    worldId: 'world-4',
    slug: 'fork-defense',
    title: 'Prevent forks',
    estMinutes: 5,
    tags: [TAGS.doubleThreat, TAGS.defense],
    prerequisites: ['world-4-fork-construction'],
    summary: 'Teach the learner to stop the fork before it exists.',
    steps: [
      guided(
        'world-4-fork-defense-guided',
        'Block the fork early',
        'Do not wait until the fork is complete. Remove the support before the double threat lands.',
        forkPrep,
        [4],
        [TAGS.doubleThreat, TAGS.defense],
        { hintColumns: [4], successMessage: 'The best defense is often a small structural move.' },
      ),
      drill(
        'world-4-fork-defense-drill-1',
        'Prevent the next fork',
        'This puzzle wants you to deny the support square, not chase the threat square.',
        pos([1, 4, 2, 4, 3, 5], 'human', 'fork denial'),
        [4],
        [TAGS.doubleThreat, TAGS.defense],
        { hintColumns: [4], successMessage: 'You stopped the fork before it split the board.' },
      ),
    ],
  }),
  lessonDef({
    id: 'world-4-forksmith',
    worldId: 'world-4',
    slug: 'forksmith',
    title: 'Forksmith',
    estMinutes: 4,
    tags: [TAGS.doubleThreat, TAGS.review],
    prerequisites: ['world-4-fork-defense'],
    bossAiId: 'forksmith',
    summary: 'The first boss that actively hunts double threats.',
    steps: [
      battleStep(
        'world-4-forksmith-battle',
        'Play Forksmith',
        'Stay alert for positions that look safe but actually split into two threats.',
        [TAGS.doubleThreat, TAGS.review],
        {
          position: forkPrep,
          coachNotes: [note('forksmith', TAGS.doubleThreat, 'Forks are the point', 'The boss wants you to miss the second threat.')],
        },
      ),
      boss(
        'world-4-forksmith-boss',
        'Fork checkpoint',
        'Name the move that forced the opponent to answer two things at once.',
        [TAGS.doubleThreat, TAGS.review],
        { successMessage: 'You now know why one block is sometimes not enough.' },
      ),
    ],
  }),
];

const world5Lessons = [
  lessonDef({
    id: 'world-5-diagonal-support',
    worldId: 'world-5',
    slug: 'diagonal-support',
    title: 'Diagonal support',
    estMinutes: 5,
    tags: [TAGS.diagonal, TAGS.review],
    prerequisites: ['world-4-forksmith'],
    summary: 'Make diagonal ideas visible by focusing on their support squares.',
    steps: [
      concept(
        'world-5-diagonal-support-concept',
        'Diagonals need support',
        'A diagonal chip matters only if the square below it is already settled or will be settled in time.',
        [TAGS.diagonal, TAGS.review],
        {
          position: diagonalPrep,
          coachNotes: [note('support', TAGS.diagonal, 'Support first', 'A diagonal is only playable when gravity says so.')],
        },
      ),
      guided(
        'world-5-diagonal-support-guided',
        'Find the support square',
        'Pick the move that makes the diagonal actually playable.',
        diagonalSupportWin,
        [4],
        [TAGS.diagonal],
        { hintColumns: [4], successMessage: 'You found the square beneath the square.' },
      ),
    ],
  }),
  lessonDef({
    id: 'world-5-staircase-reading',
    worldId: 'world-5',
    slug: 'staircase-reading',
    title: 'Staircase reading',
    estMinutes: 5,
    tags: [TAGS.diagonal, TAGS.threat],
    prerequisites: ['world-5-diagonal-support'],
    summary: 'Read zig-zags and staircases as real tactical objects, not decorative geometry.',
    steps: [
      drill(
        'world-5-staircase-reading-drill-1',
        'Read the staircase',
        'Choose the move that keeps the diagonal staircase alive.',
        pos([4, 5, 5, 6, 6, 7], 'human', 'staircase pattern'),
        [4],
        [TAGS.diagonal],
        { hintColumns: [4], successMessage: 'You saw the diagonal shape before it became obvious.' },
      ),
      puzzle(
        'world-5-staircase-reading-puzzle-1',
        'Playable diagonal',
        'A diagonal can look unfinished for a long time before the last support arrives.',
        pos([3, 4, 4, 5, 5, 6], 'human', 'playable diagonal'),
        [6],
        [TAGS.diagonal],
        { hintColumns: [6], coachNotes: [note('playable-diagonal', TAGS.diagonal, 'Playable diagonal', 'Look for the last support square, not only the top chip.')], successMessage: 'You focused on the support, not just the visible line.' },
      ),
    ],
  }),
  lessonDef({
    id: 'world-5-hidden-geometry',
    worldId: 'world-5',
    slug: 'hidden-geometry',
    title: 'Hidden geometry',
    estMinutes: 5,
    tags: [TAGS.diagonal, TAGS.defense],
    prerequisites: ['world-5-staircase-reading'],
    summary: 'Practice the idea that diagonals are dangerous because they are harder to see early.',
    steps: [
      guided(
        'world-5-hidden-geometry-guided',
        'Spot the hidden diagonal',
        'Read the support squares, then the diagonal itself.',
        pos([2, 3, 3, 4, 4, 5], 'human', 'hidden diagonal'),
        [5],
        [TAGS.diagonal, TAGS.defense],
        { hintColumns: [5], successMessage: 'You respected the geometry of the board.' },
      ),
      drill(
        'world-5-hidden-geometry-drill-1',
        'Diagonal defense',
        'A good defense often blocks a support square instead of the visible top chip.',
        pos([1, 2, 2, 3, 3, 4], 'human', 'diagonal defense'),
        [4],
        [TAGS.diagonal, TAGS.defense],
        { hintColumns: [4], successMessage: 'You stopped the diagonal where it had to grow from.' },
      ),
    ],
  }),
  lessonDef({
    id: 'world-5-diagonal-djinn',
    worldId: 'world-5',
    slug: 'diagonal-djinn',
    title: 'Diagonal Djinn',
    estMinutes: 4,
    tags: [TAGS.diagonal, TAGS.review],
    prerequisites: ['world-5-hidden-geometry'],
    bossAiId: 'diagonal-djinn',
    summary: 'A boss that specializes in hidden diagonal pressure and support traps.',
    steps: [
      battleStep(
        'world-5-diagonal-djinn-battle',
        'Play Diagonal Djinn',
        'Keep your eyes on the support squares and do not let the board surprise you diagonally.',
        [TAGS.diagonal, TAGS.review],
        {
          position: diagonalPrep,
          coachNotes: [note('djinn', TAGS.diagonal, 'The boss hides in the structure', 'If you only read the top row, you miss the real threat.')],
        },
      ),
      boss(
        'world-5-diagonal-djinn-boss',
        'Diagonal checkpoint',
        'Explain the support square that mattered most in the last game.',
        [TAGS.diagonal, TAGS.review],
        { successMessage: 'You can now see diagonal danger before it becomes obvious.' },
      ),
    ],
  }),
];

const world6Lessons = [
  lessonDef({
    id: 'world-6-parity-basics',
    worldId: 'world-6',
    slug: 'parity-basics',
    title: 'Parity basics',
    estMinutes: 6,
    tags: [TAGS.parity, TAGS.review],
    prerequisites: ['world-5-diagonal-djinn'],
    summary: 'Introduce odd/even access in plain language and visual patterns.',
    steps: [
      concept(
        'world-6-parity-basics-concept',
        'Not every square belongs to you',
        'A square only matters if you can actually claim it on your turn. Gravity and move order decide that.',
        [TAGS.parity, TAGS.review],
        {
          position: parityPrep,
          coachNotes: [note('parity-core', TAGS.parity, 'Access matters', 'Who can reach the square on the right turn matters more than how pretty it looks.')],
        },
      ),
      guided(
        'world-6-parity-basics-guided',
        'Who gets the square?',
        'Choose the move that leaves the critical square in your control.',
        parityPrep,
        [4],
        [TAGS.parity],
        { hintColumns: [4], successMessage: 'You saw the square as an access problem, not just a picture.' },
      ),
    ],
  }),
  lessonDef({
    id: 'world-6-odd-even-access',
    worldId: 'world-6',
    slug: 'odd-even-access',
    title: 'Odd-even access',
    estMinutes: 6,
    tags: [TAGS.parity, TAGS.endgame],
    prerequisites: ['world-6-parity-basics'],
    summary: 'Show how a key square can be poisoned or protected by move parity.',
    steps: [
      drill(
        'world-6-odd-even-access-drill-1',
        'Take the accessible square',
        'Pick the move that keeps the critical access for your side.',
        pos([4, 3, 4, 3, 5, 2], 'human', 'access test'),
        [5],
        [TAGS.parity],
        { hintColumns: [5], successMessage: 'You protected the square by understanding timing.' },
      ),
      puzzle(
        'world-6-odd-even-access-puzzle-1',
        'Poisoned square',
        'The obvious move gives away access. The quieter move keeps the parity edge.',
        pos([2, 4, 2, 4, 3, 5], 'human', 'poisoned square'),
        [3],
        [TAGS.parity, TAGS.defense],
        { hintColumns: [3], coachNotes: [note('poison', TAGS.parity, 'Poisoned move', 'Sometimes the move that looks active gives the square away.')], successMessage: 'You kept the key square from slipping away.' },
      ),
    ],
  }),
  lessonDef({
    id: 'world-6-poisoned-moves',
    worldId: 'world-6',
    slug: 'poisoned-moves',
    title: 'Poisoned moves',
    estMinutes: 6,
    tags: [TAGS.parity, TAGS.defense],
    prerequisites: ['world-6-odd-even-access'],
    summary: 'Teach the learner to avoid setup moves that hand the opponent the key access point.',
    steps: [
      guided(
        'world-6-poisoned-moves-guided',
        'Avoid the poison',
        'The active-looking move is not always the healthy one.',
        poisonedParityPrep,
        [4],
        [TAGS.parity, TAGS.defense],
        { hintColumns: [4], successMessage: 'You avoided the move that would have opened the door for them.' },
      ),
      drill(
        'world-6-poisoned-moves-drill-1',
        'Make them fill underneath',
        'Use the move that forces the opponent to occupy the square below the target.',
        parityPrep,
        [5],
        [TAGS.parity],
        { hintColumns: [5], successMessage: 'You forced the board to work against the opponent.' },
      ),
    ],
  }),
  lessonDef({
    id: 'world-6-parity-phantom',
    worldId: 'world-6',
    slug: 'parity-phantom',
    title: 'Parity Phantom',
    estMinutes: 4,
    tags: [TAGS.parity, TAGS.review],
    prerequisites: ['world-6-poisoned-moves'],
    bossAiId: 'parity-phantom',
    summary: 'The hardest conceptual boss so far, built around access, timing, and odd-even traps.',
    steps: [
      battleStep(
        'world-6-parity-phantom-battle',
        'Play Parity Phantom',
        'This boss wins by making you think about the wrong square at the wrong time.',
        [TAGS.parity, TAGS.review],
        {
          position: parityPrep,
          coachNotes: [note('phantom', TAGS.parity, 'Timing is the whole trick', 'The phantom is a timing boss, not a brute-force boss.')],
        },
      ),
      boss(
        'world-6-parity-phantom-boss',
        'Parity checkpoint',
        'Summarize who really owned the critical square.',
        [TAGS.parity, TAGS.review],
        { successMessage: 'You have a practical version of parity now, not just vocabulary.' },
      ),
    ],
  }),
];

const world7Lessons = [
  lessonDef({
    id: 'world-7-opening-rules',
    worldId: 'world-7',
    slug: 'opening-rules',
    title: 'Opening rules',
    estMinutes: 5,
    tags: [TAGS.opening, TAGS.center],
    prerequisites: ['world-6-parity-phantom'],
    summary: 'Teach practical opening principles without pretending memorization is the whole game.',
    steps: [
      concept(
        'world-7-opening-rules-concept',
        'Start with the center',
        'The opening is about flexibility. The center usually gives the best base for that flexibility.',
        [TAGS.opening, TAGS.center],
        {
          position: empty,
          coachNotes: [note('opening-rules', TAGS.opening, 'A good opening is small and durable', 'The move should stay useful after several replies.')],
        },
      ),
      guided(
        'world-7-opening-rules-guided',
        'Best first move',
        'On a fresh board, answer with the move that preserves the most future choices.',
        empty,
        [4],
        [TAGS.opening, TAGS.center],
        { hintColumns: [4], successMessage: 'You chose a move that stays relevant after the board fills.' },
      ),
    ],
  }),
  lessonDef({
    id: 'world-7-symmetry-mirror',
    worldId: 'world-7',
    slug: 'symmetry-mirror',
    title: 'Symmetry and mirror play',
    estMinutes: 5,
    tags: [TAGS.opening, TAGS.review],
    prerequisites: ['world-7-opening-rules'],
    summary: 'Teach the learner to read mirrored responses and not break structure too early.',
    steps: [
      drill(
        'world-7-symmetry-mirror-drill-1',
        'Balance the mirror',
        'Answer the side probe with the balancing move unless a tactic gives you something stronger.',
        mirrorPrep,
        [6],
        [TAGS.opening],
        { hintColumns: [6], successMessage: 'You preserved symmetry until a real reason to break it appeared.' },
      ),
      puzzle(
        'world-7-symmetry-mirror-puzzle-1',
        'Mirror or punish?',
        'If the opponent mirrored your move, ask whether the right response is still center pressure.',
        mirrorPunish,
        [2],
        [TAGS.opening, TAGS.center],
        { hintColumns: [2], coachNotes: [note('mirror', TAGS.opening, 'Mirrors are useful until they are not', 'Sometimes the best response is a quiet imbalance.')], successMessage: 'You looked for the practical reply, not the textbook one.' },
      ),
    ],
  }),
  lessonDef({
    id: 'world-7-practical-lines',
    worldId: 'world-7',
    slug: 'practical-lines',
    title: 'Practical opening lines',
    estMinutes: 5,
    tags: [TAGS.opening, TAGS.threat],
    prerequisites: ['world-7-symmetry-mirror'],
    summary: 'Use a few compact opening lines to make the first six plies feel navigable.',
    steps: [
      guided(
        'world-7-practical-lines-guided',
        'Keep the line healthy',
        'Choose the move that stays structurally sound after the first reply.',
        pos([4, 3, 4, 3], 'human', 'practical opening'),
        [4],
        [TAGS.opening],
        { hintColumns: [4], successMessage: 'You kept the opening line practical instead of fancy.' },
      ),
      drill(
        'world-7-practical-lines-drill-1',
        'Good response to center',
        'If the opponent already took center, use the most useful adjacent column rather than chasing the edge.',
        pos([4, 4, 3, 3], 'human', 'response to center'),
        [3, 5],
        [TAGS.opening, TAGS.center],
        { hintColumns: [3, 5], successMessage: 'You chose the reply that still plays for the middle.' },
      ),
    ],
  }),
  lessonDef({
    id: 'world-7-mirror-master',
    worldId: 'world-7',
    slug: 'mirror-master',
    title: 'Mirror Master',
    estMinutes: 4,
    tags: [TAGS.opening, TAGS.review],
    prerequisites: ['world-7-practical-lines'],
    bossAiId: 'mirror-master',
    summary: 'An opening-book boss that punishes careless first-six-ply structures.',
    steps: [
      battleStep(
        'world-7-mirror-master-battle',
        'Play Mirror Master',
        'Stay calm in the opening. The boss wants a structural mistake more than a tactical blunder.',
        [TAGS.opening, TAGS.review],
        {
          position: mirrorPrep,
          coachNotes: [note('mirror-master', TAGS.opening, 'Opening-book pressure', 'Good opening play stays flexible and does not overcommit.')],
        },
      ),
      boss(
        'world-7-mirror-master-boss',
        'Opening checkpoint',
        'Say which early move most improved your future flexibility.',
        [TAGS.opening, TAGS.review],
        { successMessage: 'You can now navigate the first few moves without panic.' },
      ),
    ],
  }),
];

const world8Lessons = [
  lessonDef({
    id: 'world-8-convert-and-defend',
    worldId: 'world-8',
    slug: 'convert-and-defend',
    title: 'Convert and defend',
    estMinutes: 6,
    tags: [TAGS.endgame, TAGS.defense],
    prerequisites: ['world-7-mirror-master'],
    summary: 'Turn better positions into wins and worse positions into calm defense.',
    steps: [
      concept(
        'world-8-convert-and-defend-concept',
        'Winning is a process',
        'In the late game, the right move is often the one that keeps your advantage clean and unforced.',
        [TAGS.endgame, TAGS.defense],
        {
          position: endgamePrep,
          coachNotes: [note('convert', TAGS.endgame, 'Convert with patience', 'Do not rush the win if the board already favors you.')],
        },
      ),
      guided(
        'world-8-convert-and-defend-guided',
        'Convert the advantage',
        'Choose the move that keeps your win intact instead of launching something speculative.',
        endgamePrep,
        [4],
        [TAGS.endgame],
        { hintColumns: [4], successMessage: 'You converted without donating counterplay.' },
      ),
    ],
  }),
  lessonDef({
    id: 'world-8-simplify-and-squeeze',
    worldId: 'world-8',
    slug: 'simplify-and-squeeze',
    title: 'Simplify and squeeze',
    estMinutes: 6,
    tags: [TAGS.endgame, TAGS.defense, TAGS.parity],
    prerequisites: ['world-8-convert-and-defend'],
    summary: 'Teach practical endgame patience, especially when a clean defense is the best move.',
    steps: [
      drill(
        'world-8-simplify-and-squeeze-drill-1',
        'Cleanest move',
        'If you already have the better position, keep the board simple.',
        pos([4, 1, 4, 2, 3, 2, 3, 6], 'human', 'simplify the board'),
        [4],
        [TAGS.endgame, TAGS.defense],
        { hintColumns: [4], successMessage: 'You avoided needless complications.' },
      ),
      puzzle(
        'world-8-simplify-and-squeeze-puzzle-1',
        'Save the draw',
        'When the win is gone, the best move may be the one that keeps the game drawable.',
        pos([2, 1, 2, 1, 3, 4, 3, 4], 'human', 'draw save'),
        [3],
        [TAGS.endgame, TAGS.defense],
        { hintColumns: [3], coachNotes: [note('draw-save', TAGS.endgame, 'Saving a draw is a skill', 'A patient defensive move is a win for your learning loop.')], successMessage: 'You protected the outcome instead of forcing it.' },
      ),
    ],
  }),
  lessonDef({
    id: 'world-8-review-mix',
    worldId: 'world-8',
    slug: 'review-mix',
    title: 'Review mix',
    estMinutes: 5,
    tags: [TAGS.review, TAGS.endgame, TAGS.parity, TAGS.doubleThreat],
    prerequisites: ['world-8-simplify-and-squeeze'],
    summary: 'A mixed checkpoint that pulls back the most important concepts from earlier worlds.',
    steps: [
      guided(
        'world-8-review-mix-guided',
        'What concept matters most?',
        'Read the board, then decide which idea controls the move: center, threat, fork, diagonal, or parity.',
        parityPrep,
        [4],
        [TAGS.review, TAGS.parity],
        { hintColumns: [4], successMessage: 'You are starting to name the concept before the move.' },
      ),
      drill(
        'world-8-review-mix-drill-1',
        'Best practical move',
        'Choose the move that keeps the endgame alive without creating a cheap tactic for the opponent.',
        endgamePrep,
        [4],
        [TAGS.endgame, TAGS.review],
        { hintColumns: [4], successMessage: 'You chose the move that survived the next reply.' },
      ),
    ],
  }),
  lessonDef({
    id: 'world-8-endgame-engine',
    worldId: 'world-8',
    slug: 'endgame-engine',
    title: 'Endgame Engine',
    estMinutes: 4,
    tags: [TAGS.endgame, TAGS.review],
    prerequisites: ['world-8-review-mix'],
    bossAiId: 'endgame-engine',
    summary: 'The strongest production battle AI, with opening book and deeper selective search.',
    steps: [
      battleStep(
        'world-8-endgame-engine-battle',
        'Play Endgame Engine',
        'This boss uses the strongest practical logic in the ladder, but it still values instant-feeling play.',
        [TAGS.endgame, TAGS.review],
        {
          position: endgamePrep,
          coachNotes: [note('engine', TAGS.endgame, 'Convert carefully', 'The engine rewards accuracy more than speed.')],
        },
      ),
      boss(
        'world-8-endgame-engine-boss',
        'Capstone prep',
        'Name the tactical idea that most often decided your last two games.',
        [TAGS.endgame, TAGS.review],
        { successMessage: 'You are ready for the exam path.' },
      ),
    ],
  }),
];

const capstoneLessons = [
  lessonDef({
    id: 'capstone-exam',
    worldId: 'capstone',
    slug: 'exam',
    title: 'Thirty-position exam',
    estMinutes: 20,
    tags: [TAGS.review, TAGS.center, TAGS.threat, TAGS.doubleThreat, TAGS.diagonal, TAGS.parity, TAGS.endgame],
    prerequisites: ['world-8-endgame-engine'],
    summary: 'A mixed exam that samples every major concept from the course.',
    steps: [
      concept(
        'capstone-exam-concept',
        'What the exam measures',
        'This checkpoint samples win-in-one, block-in-one, center control, threat-building, fork spotting, diagonal support, and parity.',
        [TAGS.review],
        {
          coachNotes: [note('exam', TAGS.review, 'Measured practice', 'The goal is to show you what stuck and what still needs review.')],
        },
      ),
      battleStep(
        'capstone-exam-battle',
        'Run the exam set',
        'Work through the positions one by one. The important part is the concept you name before you move.',
        [TAGS.review],
        { position: parityPrep },
      ),
      puzzle(
        'capstone-exam-puzzle',
        'One more mixed position',
        'Pick the best move and identify the concept tag it belongs to.',
        forkPrep,
        [4],
        [TAGS.doubleThreat, TAGS.review],
        { hintColumns: [4], successMessage: 'You kept the mixed exam grounded in one concept at a time.' },
      ),
    ],
  }),
  lessonDef({
    id: 'capstone-gauntlet',
    worldId: 'capstone',
    slug: 'gauntlet',
    title: 'Final gauntlet',
    estMinutes: 25,
    tags: [TAGS.review, TAGS.endgame],
    prerequisites: ['capstone-exam'],
    bossAiId: 'oracle',
    summary: 'Beat or draw three bosses in sequence and close the loop on the curriculum.',
    steps: [
      battleStep(
        'capstone-gauntlet-battle-1',
        'Boss one',
        'Start the gauntlet with the most tactical boss you have already met.',
        [TAGS.review, TAGS.endgame],
        { position: forkPrep },
      ),
      battleStep(
        'capstone-gauntlet-battle-2',
        'Boss two',
        'Switch to the strongest positional check you have seen so far.',
        [TAGS.review, TAGS.endgame],
        { position: parityPrep },
      ),
      boss(
        'capstone-gauntlet-boss',
        'Final wrap-up',
        'Finish by naming the concept that saved the most games across the course.',
        [TAGS.review, TAGS.endgame],
        { successMessage: 'The course is complete, and the review loop can keep doing the rest.' },
      ),
    ],
  }),
];

export const curriculumLessons: LessonDef[] = [
  ...world0Lessons,
  ...world1Lessons,
  ...world2Lessons,
  ...world3Lessons,
  ...world4Lessons,
  ...world5Lessons,
  ...world6Lessons,
  ...world7Lessons,
  ...world8Lessons,
  ...capstoneLessons,
];

export const curriculumWorlds: WorldDef[] = [
  world({
    id: 'world-0',
    order: 0,
    title: 'Zero to First Move',
    shortTitle: 'Start',
    subtitle: 'Learn the basic rules',
    estHours: 0.25,
    goal: 'Learn the basic rules',
    conceptTags: [TAGS.rules, TAGS.winIn1, TAGS.blockIn1],
    bossAiId: 'warmup-bot',
    prerequisites: [],
    unlocks: ['world-1'],
    lessonIds: world0Lessons.map((item) => item.id),
  }),
  world({
    id: 'world-1',
    order: 1,
    title: 'Never Miss the Obvious',
    shortTitle: 'Basics',
    subtitle: 'Prevent common blunders',
    estHours: 0.75,
    goal: 'Prevent common blunders',
    conceptTags: [TAGS.winIn1, TAGS.blockIn1, TAGS.review],
    bossAiId: 'block-baron',
    prerequisites: ['world-0'],
    unlocks: ['world-2'],
    lessonIds: world1Lessons.map((item) => item.id),
  }),
  world({
    id: 'world-2',
    order: 2,
    title: 'Center Control',
    shortTitle: 'Center',
    subtitle: 'Learn how to control the center',
    estHours: 1,
    goal: 'Learn how to control the center',
    conceptTags: [TAGS.center, TAGS.opening],
    bossAiId: 'center-sentinel',
    prerequisites: ['world-1'],
    unlocks: ['world-3'],
    lessonIds: world2Lessons.map((item) => item.id),
  }),
  world({
    id: 'world-3',
    order: 3,
    title: 'Build Threats',
    shortTitle: 'Threats',
    subtitle: 'Learn how to force responses through threats',
    estHours: 1,
    goal: 'Learn how to force responses through threats',
    conceptTags: [TAGS.threat, TAGS.review],
    bossAiId: 'threat-smith',
    prerequisites: ['world-2'],
    unlocks: ['world-4'],
    lessonIds: world3Lessons.map((item) => item.id),
  }),
  world({
    id: 'world-4',
    order: 4,
    title: 'Double Threats and Forks',
    shortTitle: 'Forks',
    subtitle: 'Learn fork threats',
    estHours: 1.25,
    goal: 'Learn fork threats',
    conceptTags: [TAGS.doubleThreat, TAGS.threat, TAGS.defense],
    bossAiId: 'forksmith',
    prerequisites: ['world-3'],
    unlocks: ['world-5'],
    lessonIds: world4Lessons.map((item) => item.id),
  }),
  world({
    id: 'world-5',
    order: 5,
    title: 'Diagonal Geometry',
    shortTitle: 'Diagonals',
    subtitle: 'Prevent diagonal attacks',
    estHours: 1,
    goal: 'Prevent diagonal attacks',
    conceptTags: [TAGS.diagonal, TAGS.defense],
    bossAiId: 'diagonal-djinn',
    prerequisites: ['world-4'],
    unlocks: ['world-6'],
    lessonIds: world5Lessons.map((item) => item.id),
  }),
  world({
    id: 'world-6',
    order: 6,
    title: 'Odd and Even',
    shortTitle: 'Parity',
    subtitle: 'Learn odd and even techniques',
    estHours: 1.75,
    goal: 'Learn odd and even techniques',
    conceptTags: [TAGS.parity, TAGS.endgame, TAGS.defense],
    bossAiId: 'parity-phantom',
    prerequisites: ['world-5'],
    unlocks: ['world-7'],
    lessonIds: world6Lessons.map((item) => item.id),
  }),
  world({
    id: 'world-7',
    order: 7,
    title: 'Openings and Anti-Blunders',
    shortTitle: 'Openings',
    subtitle: 'Learn optimal openings',
    estHours: 1,
    goal: 'Learn optimal openings',
    conceptTags: [TAGS.opening, TAGS.center, TAGS.threat],
    bossAiId: 'mirror-master',
    prerequisites: ['world-6'],
    unlocks: ['world-8'],
    lessonIds: world7Lessons.map((item) => item.id),
  }),
  world({
    id: 'world-8',
    order: 8,
    title: 'Conversion and Sparring',
    shortTitle: 'Endgame',
    subtitle: 'Learn conversions and sparring',
    estHours: 1.25,
    goal: 'Learn conversions and sparring',
    conceptTags: [TAGS.endgame, TAGS.defense, TAGS.parity],
    bossAiId: 'endgame-engine',
    prerequisites: ['world-7'],
    unlocks: ['capstone'],
    lessonIds: world8Lessons.map((item) => item.id),
  }),
  world({
    id: 'capstone',
    order: 9,
    title: 'Capstone',
    shortTitle: 'Exam',
    subtitle: 'Review and the Final Gauntlet',
    estHours: 0.75,
    goal: 'Review and the Final Gauntlet',
    conceptTags: [TAGS.review, TAGS.endgame],
    bossAiId: 'oracle',
    prerequisites: ['world-8'],
    unlocks: [],
    lessonIds: capstoneLessons.map((item) => item.id),
  }),
];

export const curriculumByWorld = new Map(curriculumWorlds.map((entry) => [entry.id, entry]));
export const curriculumByLesson = new Map(curriculumLessons.map((entry) => [entry.id, entry]));
