import type { AIProfile } from './types';

export const AI_PROFILES: readonly AIProfile[] = [
  {
    id: 0,
    name: 'Warmup Bot',
    depth: 1,
    useOpeningBook: false,
    iterativeDeepening: false,
    searchNodeLimit: 256,
    centerWeight: 6,
    threatWeight: 20,
    doubleThreatWeight: 40,
    diagonalWeight: 2,
    parityWeight: 0,
    fallbackBias: 2,
    analysisDepth: 2,
  },
  {
    id: 1,
    name: 'Block Baron',
    depth: 2,
    useOpeningBook: true,
    iterativeDeepening: false,
    searchNodeLimit: 512,
    centerWeight: 8,
    threatWeight: 30,
    doubleThreatWeight: 60,
    diagonalWeight: 3,
    parityWeight: 0,
    fallbackBias: 3,
    analysisDepth: 3,
  },
  {
    id: 2,
    name: 'Center Sentinel',
    depth: 3,
    useOpeningBook: true,
    iterativeDeepening: true,
    searchNodeLimit: 1_500,
    centerWeight: 12,
    threatWeight: 34,
    doubleThreatWeight: 72,
    diagonalWeight: 5,
    parityWeight: 0,
    fallbackBias: 4,
    analysisDepth: 4,
  },
  {
    id: 3,
    name: 'Threat Smith',
    depth: 4,
    useOpeningBook: true,
    iterativeDeepening: true,
    searchNodeLimit: 3_500,
    centerWeight: 12,
    threatWeight: 42,
    doubleThreatWeight: 88,
    diagonalWeight: 6,
    parityWeight: 0,
    fallbackBias: 5,
    analysisDepth: 5,
  },
  {
    id: 4,
    name: 'Forksmith',
    depth: 5,
    useOpeningBook: true,
    iterativeDeepening: true,
    searchNodeLimit: 7_500,
    centerWeight: 12,
    threatWeight: 48,
    doubleThreatWeight: 116,
    diagonalWeight: 7,
    parityWeight: 0,
    fallbackBias: 6,
    analysisDepth: 6,
  },
  {
    id: 5,
    name: 'Diagonal Djinn',
    depth: 5,
    useOpeningBook: true,
    iterativeDeepening: true,
    searchNodeLimit: 8_500,
    centerWeight: 11,
    threatWeight: 44,
    doubleThreatWeight: 110,
    diagonalWeight: 12,
    parityWeight: 2,
    fallbackBias: 6,
    analysisDepth: 6,
  },
  {
    id: 6,
    name: 'Parity Phantom',
    depth: 6,
    useOpeningBook: true,
    iterativeDeepening: true,
    searchNodeLimit: 15_000,
    centerWeight: 10,
    threatWeight: 48,
    doubleThreatWeight: 120,
    diagonalWeight: 10,
    parityWeight: 14,
    fallbackBias: 7,
    analysisDepth: 7,
  },
  {
    id: 7,
    name: 'Mirror Master',
    depth: 6,
    useOpeningBook: true,
    iterativeDeepening: true,
    searchNodeLimit: 18_000,
    centerWeight: 12,
    threatWeight: 52,
    doubleThreatWeight: 128,
    diagonalWeight: 10,
    parityWeight: 16,
    fallbackBias: 8,
    analysisDepth: 8,
  },
  {
    id: 8,
    name: 'Endgame Engine',
    depth: 8,
    useOpeningBook: true,
    iterativeDeepening: true,
    searchNodeLimit: 32_000,
    centerWeight: 12,
    threatWeight: 56,
    doubleThreatWeight: 144,
    diagonalWeight: 12,
    parityWeight: 20,
    fallbackBias: 8,
    analysisDepth: 10,
  },
];

export const ORACLE_ANALYSIS: AIProfile = {
  id: 99,
  name: 'Oracle',
  depth: 9,
  useOpeningBook: true,
  iterativeDeepening: true,
  searchNodeLimit: 60_000,
  centerWeight: 12,
  threatWeight: 60,
  doubleThreatWeight: 160,
  diagonalWeight: 14,
  parityWeight: 24,
  fallbackBias: 8,
  analysisDepth: 12,
};

export function getAIProfile(id: number): AIProfile {
  return AI_PROFILES.find((profile) => profile.id === id) ?? AI_PROFILES[0];
}

